spring:
  batch:
    initialize-schema: always
  cache:
    type: simple
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Nupur@29
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

input:
  xml:
    file: /Users/surbhichaudhary/Downloads/blog-projects/converter-batch/data/input/xmlFile.xml
output:
  xml:
    file: /Users/surbhichaudhary/Downloads/blog-projects/converter-batch/data/output/file.json